export const currencyCodes = [
  "USD",
  "EUR",
  "GBP",
  "INR",
  "MYR",
  "SGD",
  "AUD",
  "CAD",
  "JPY",
  "CNY",
  "THB",
  "IDR",
  "PHP",
  "VND",
  "KRW",
  "AED",
  "CHF",
  "NZD",
  "HKD",
  "ZAR",
  "MXN",
  "BRL",
  "SAR",
  "PKR",
  "BDT",
  "LKR",
  "NPR",
  "EGP",
  "TRY",
] as const;

export const currencyLabels: Record<(typeof currencyCodes)[number], string> = {
  USD: "US Dollar",
  EUR: "Euro",
  GBP: "British Pound",
  INR: "Indian Rupee",
  MYR: "Malaysian Ringgit",
  SGD: "Singapore Dollar",
  AUD: "Australian Dollar",
  CAD: "Canadian Dollar",
  JPY: "Japanese Yen",
  CNY: "Chinese Yuan",
  THB: "Thai Baht",
  IDR: "Indonesian Rupiah",
  PHP: "Philippine Peso",
  VND: "Vietnamese Dong",
  KRW: "South Korean Won",
  AED: "UAE Dirham",
  CHF: "Swiss Franc",
  NZD: "New Zealand Dollar",
  HKD: "Hong Kong Dollar",
  ZAR: "South African Rand",
  MXN: "Mexican Peso",
  BRL: "Brazilian Real",
  SAR: "Saudi Riyal",
  PKR: "Pakistani Rupee",
  BDT: "Bangladeshi Taka",
  LKR: "Sri Lankan Rupee",
  NPR: "Nepalese Rupee",
  EGP: "Egyptian Pound",
  TRY: "Turkish Lira",
};
